### ISSUE TITLE
support PCRE regexps

### ISSUE THREAD

**Issue by mtk** [mkcms/interactive-align#5]
`pcre-mode` 'advises' `read-regexp` so that perl regexp syntax can be used instead of elisp.  but `ialign` (i guess because of the 'i' :-)) reads the regexp on its own, thus ignoring `pcre-mode`'s influence.  can you modify `ialign-update` so that accepts PCRE regexps?  to do so, you could (1) add a check for `pcre-mode` and call `rxt-pcre-to-elisp` on the value returned by `minibuffer-contents-no-properties` or (2) define a tiny ialign function (e.g. `ialign-fetch-minibuffer-contents`) to wrap your call to `minibuffer-contents-no-properties` which could be easily 'advised' to convert PCRE syntax to elisp from an init.el or pcre2el.el itself. thoughts/comments?

**Comment by mkcms** [comment]
Thanks for the suggestion. It seems like a good feature, I will look into implementing it this weekend.

**Comment by mkcms** [comment]
I will probably add a toggle, either a variable or a command with a keybinding which would change the syntax during `ialign`. Of course I have to look into this `pcre-mode` package first.

**Comment by mkcms** [comment]
I just pushed commit  eca40b8 to master, which allows you to use PCRE regexp syntax, please let me know how/if it works.

To use it, do `C-c C-p` (`ialign-toggle-pcre-mode`) during `ialign` session, this will make ialign treat the input as a PCRE regexp. It will be implicitly converted to an elisp regexp during alignment. Of course, this requires that you have the `pcre2el` library installed.
