### ISSUE TITLE
New release? :)

### ISSUE THREAD

**Issue by mattiasb** [mkcms/interactive-align#7]
Hey!

I just saw that a feature I've been missing in `ialign` was implemented four years ago ([support PCRE regexps](https://github.com/mkcms/interactive-align/issues/5)). 😃

I'll pin `ialign` to `melpa` i nmy own config for now, but maybe it's time for a new release? 😉

Thanks a lot for `ialign` btw. I've been using it daily for years!

**Comment by mkcms** [comment]
Hi! 
Indeed, it has been a while since last release, so I just pushed a new `v0.5.0` tag this morning.

> Thanks a lot for ialign btw. I've been using it daily for years!

Thank you!
